### ISSUE TITLE
Syslog collection support

### ISSUE THREAD

**Issue by exptom** [charlescng/docker-containers#15]
From what I can see there is no syslog collection support in the docker image. (please correct me if I am wrong and let me know how to use it!).

Is this a feature you are likely to add?
Would you accept a PR that added it?

**Comment by charlescng** [comment]
I don't have time to work on this but PRs are welcomed.

**Comment by exptom** [comment]
See PR #17

**Comment by charlescng** [comment]
Implemented in #20
