### ISSUE TITLE
Image and Log date/time discrepancy.. UTC vs TZ

### ISSUE THREAD

**Issue by bcookatpcsd** [charlescng/docker-containers#25]
Hello sir, 

I have a graph: 
![image](https://user-images.githubusercontent.com/55087301/146190369-98a75124-57c8-4918-aeee-7b62f53ec773.png)

and after editing the log format to show the timezone:
![image](https://user-images.githubusercontent.com/55087301/146190490-6d442c3c-3607-4c67-8b43-28307b94e9b9.png)

The image creation is not the same as the logfile.. 

From 1:15 to 3:45 the power was out the graph shows 6:15, which would be UTC (I'm EST -5 atm) 

#####  Timezones info  #####

 o Date                 Wednesday, 15-Dec-21 07:51:46 EST
 o PHP                  -05:00
 o MariaDB              -05:00

./poller.php -d shows that it should be correct.. 

TZ was/is set correctly in the docker-compose for observium and when I enter the container it is also appearing correctly in env

Suggestions?

**Comment by bcookatpcsd** [comment]
so /etc/localtime in the docker image is still pointing to 

/etc/localtime -> /usr/share/zoneinfo/Etc/UTC

root@db3406aabc73:/# rm /etc/localtime
root@db3406aabc73:/# ln -s /usr/share/zoneinfo/America/New_York /etc/localtime

Got my graph to sync with the system time.. 

According to googling on the interweb this is a constant issue and I've not found an issue other than cp'ing the zonefile .. but I've yet to figure how to make it work correctly.. 

Again thank you for your time and efforts..

**Comment by charlescng** [comment]
The timezone are all using the environment variable.

![image](https://user-images.githubusercontent.com/6034184/149680788-a881398c-1e63-4dea-a9de-c4ea4d7f4ff7.png)

MariaDB is also reporting the correct time and timezone.

You can try mounting the host `/etc/localtime` if you have it set to the "right" timezone.
```
volumes:
  - /etc/localtime:/etc/localtime:ro
 ```
