### ISSUE TITLE
Update Observium version

### ISSUE THREAD

**Issue by exptom** [charlescng/docker-containers#27]
Could you release an updated container with the latest Observium CE? `22.5 (25th May 2022) `
Thanks :)

**Comment by charlescng** [comment]
I'm doing a build and will give it a test.

**Comment by charlescng** [comment]
New image pushed with `22.5.12042 (24th May 2022)` and moved `[baseimage](https://github.com/phusion/baseimage-docker)` up to `[focal-1.2.0](https://github.com/phusion/baseimage-docker/releases/tag/focal-1.2.0)`
