### ISSUE TITLE
Is this still the source for the image on Docker hub?

### ISSUE THREAD

**Issue by imcdona** [charlescng/docker-containers#38]
The latest `uberchuckie/observium` image was uploaded to Docker hub on October 23rd, 2023.  Meanwhile the most recent commit made to this repo was 7 months ago.

Is this repo still the source of the` uberchuckie/observium` docker image?

**Comment by charlescng** [comment]
Yes, most of the updates don't need changes. A new container build is sufficient.

Thanks for the pull request.
